MVC Sample/MvcSampleWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcSampleWebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Sample Web Application.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "";

            return View();
        }
    }
}

MVC Sample/MvcSampleWebApp/Controllers/PrintJobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcSampleWebApp.Models;

namespace MvcSampleWebApp.Controllers
{
    public class PrintJobsController : Controller
    {
        private PrintJobDBContext db = new PrintJobDBContext();

        //
        // GET: /PrintJobs/
        [Authorize]
        public ActionResult Index()
        {
            return View(db.PrintJobs.ToList());
        }

        //
        // GET: /PrintJobs/Details/5

        public ActionResult Details(int id = 0)
        {
            PrintJob printjob = db.PrintJobs.Find(id);
            if (printjob == null)
            {
                return HttpNotFound();
            }
            return View(printjob);
        }

        //
        // GET: /PrintJobs/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /PrintJobs/Create

        [HttpPost]
        public ActionResult Create(PrintJob printjob)
        {
            if (ModelState.IsValid)
            {
                db.PrintJobs.Add(printjob);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(printjob);
        }

        //
        // GET: /PrintJobs/Edit/5

        public ActionResult Edit(int id = 0)
        {
            PrintJob printjob = db.PrintJobs.Find(id);
            if (printjob == null)
            {
                return HttpNotFound();
            }
            return View(printjob);
        }

        //
        // POST: /PrintJobs/Edit/5

        [HttpPost]
        public ActionResult Edit(PrintJob printjob)
        {
            if (ModelState.IsValid)
            {
                db.Entry(printjob).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(printjob);
        }

        //
        // GET: /PrintJobs/Delete/5

        public ActionResult Delete(int id = 0)
        {
            PrintJob printjob = db.PrintJobs.Find(id);
            if (printjob == null)
            {
                return HttpNotFound();
            }
            return View(printjob);
        }

        //
        // POST: /PrintJobs/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            PrintJob printjob = db.PrintJobs.Find(id);
            db.PrintJobs.Remove(printjob);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MVC Sample/MvcSampleWebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        This is a sample deployment of the MVC 4 Web Application using VS 2012 and The Entity Framework
    </p>
</article>

<aside>
    <p>&nbsp;</p>
   
</aside>

MVC Sample/MvcSampleWebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>916.393.1255</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Developersong@gmail.com">Developersong@gmail.com</a></span>
    </p>
    
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        6241 Riverside Blvd 201<br />
        Sacramento, CA. 95831
    </p>
</section>

MVC Sample/MvcSampleWebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
            @Html.ActionLink("Print Jobs","Index","PrintJobs")
            </p>
       